plugins {
    id 'com.android.application'
}

android {
    namespace 'com.protocol.furnacechemistry'
    compileSdk 35

    defaultConfig {
        applicationId "com.protocol.furnacechemistry"
        minSdk 24
        targetSdk 35
        versionCode 15
        versionName "15.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
