const SHEETS={USERS:'Users',HEATS:'Heats',GRADES:'Grades',MATERIALS:'Addition Materials',MAP:'Grade Material Map'};
const ELEMENTS=['Cu','Zn','Pb','Sn','Fe','Ni','Al','Mn','Si','As','Mg','P','Bi','Sb','Other'];
function doGet(){return json_({ok:true,service:'Furnace Chemistry Control',version:'11.0',message:'Backend is running'});}
function doPost(e){try{const request=JSON.parse((e.postData&&e.postData.contents)||'{}'),user=authenticateUser_(request.email,request.pin);if(request.action==='bootstrap')return json_({ok:true,email:user.email,name:user.name,role:user.role,heats:getHeats_(),grades:getGrades_(),materials:getMaterials_(),materialMaps:getMaterialMaps_()});if(request.action==='saveHeat'){requireSupervisor_(user);saveHeat_(request.heat,user.email);return json_({ok:true});}if(request.action==='completeHeat'){requireSupervisor_(user);completeHeat_(request.heatId,user.email);return json_({ok:true});}throw new Error('Unknown action.');}catch(error){return json_({ok:false,error:String(error.message||error)});}}
function setupWorkbookV11(){const ss=SpreadsheetApp.getActiveSpreadsheet(),users=getOrCreate_(ss,SHEETS.USERS,['Email','Name','Role','Active','PIN']),heats=getOrCreate_(ss,SHEETS.HEATS,['ID','Heat No','Grade','Furnace','Melt Weight kg','Status','Created At','Created By','Recommended Additions','Chemistry JSON','Completed At','Completed By','Predicted JSON','Grade Revision','Calculator Version','Approval Confirmed']);const gradeHeaders=['Grade','Sample Mode','Balance Element','Correction Base'];ELEMENTS.forEach(el=>gradeHeaders.push(el+' Standard Min',el+' Target Min',el+' Target Max',el+' Standard Max'));gradeHeaders.push('Warning Correction %','Approval Correction %','Maximum Correction %','Rounding kg','Addition Instructions','Revision','Active');const grades=getOrCreate_(ss,SHEETS.GRADES,gradeHeaders),materialHeaders=['Material Name','Active','Primary Element','Default','Recovery %'].concat(ELEMENTS.map(el=>el+' %')).concat(['Notes','Rounding kg','Max Stage kg','Approval Above kg','Sequence','Min Add Temp C','Max Add Temp C','Revision']).concat(ELEMENTS.map(el=>el+' Recovery %')),materials=getOrCreate_(ss,SHEETS.MATERIALS,materialHeaders),map=getOrCreate_(ss,SHEETS.MAP,['Grade','Element','Preferred Material','Alternative Material','Supervisor Selectable','Active']);ensureHeaders_(heats,['ID','Heat No','Grade','Furnace','Melt Weight kg','Status','Created At','Created By','Recommended Additions','Chemistry JSON','Completed At','Completed By','Predicted JSON','Grade Revision','Calculator Version','Approval Confirmed']);[users,heats,grades,materials,map].forEach(formatSheet_);users.getRange('C2:C').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['supervisor','management'],true).build());users.getRange('D2:D').insertCheckboxes();SpreadsheetApp.flush();return 'Version 11 setup complete';}
function authenticateUser_(emailValue,pinValue){const email=String(emailValue||'').toLowerCase().trim(),pin=String(pinValue||'').trim();if(!email||!pin)throw new Error('Email and PIN are required.');const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.USERS);if(!sheet||sheet.getLastRow()<2)throw new Error('No users are configured.');const rows=sheet.getRange(2,1,sheet.getLastRow()-1,5).getDisplayValues(),found=rows.find(r=>String(r[0]).toLowerCase().trim()===email);if(!found)throw new Error('Email is not authorized.');const active=String(found[3]).toLowerCase();if(!(active==='true'||active==='yes'||active==='1'))throw new Error('This user is inactive.');if(String(found[4]).trim()!==pin)throw new Error('Incorrect PIN.');const role=String(found[2]).toLowerCase().trim();if(role!=='supervisor'&&role!=='management')throw new Error('User role must be supervisor or management.');return{email,name:String(found[1]),role};}
function requireSupervisor_(user){if(user.role!=='supervisor')throw new Error('View-only account: supervisors alone can change furnace data.');}
function saveHeat_(heat,email){if(!heat||!heat.heatNo||!heat.grade||!(Number(heat.weight)>0))throw new Error('Heat number, grade and melt weight are required.');const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.HEATS);ensureHeaders_(sheet,['ID','Heat No','Grade','Furnace','Melt Weight kg','Status','Created At','Created By','Recommended Additions','Chemistry JSON','Completed At','Completed By','Predicted JSON','Grade Revision','Calculator Version','Approval Confirmed']);const lock=LockService.getDocumentLock();lock.waitLock(10000);try{sheet.appendRow([heat.id||Utilities.getUuid(),heat.heatNo,heat.grade,heat.furnace||'',Number(heat.weight),heat.status||'Correction due',new Date(),email,heat.additions||'',JSON.stringify(heat.chemistry||{}),'','',JSON.stringify(heat.predicted||{}),heat.gradeRevision||'',heat.calculatorVersion||'11.0',heat.approvalConfirmed===true]);}finally{lock.releaseLock();}}
function completeHeat_(heatId,email){const id=String(heatId||'').trim();if(!id)throw new Error('Heat ID is required.');const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.HEATS);if(!sheet||sheet.getLastRow()<2)throw new Error('Heat was not found.');const ids=sheet.getRange(2,1,sheet.getLastRow()-1,1).getDisplayValues(),index=ids.findIndex(r=>String(r[0]).trim()===id);if(index<0)throw new Error('Heat was not found. Sync and try again.');const row=index+2,lock=LockService.getDocumentLock();lock.waitLock(10000);try{sheet.getRange(row,6).setValue('Correction completed');sheet.getRange(row,11).setValue(new Date());sheet.getRange(row,12).setValue(email);}finally{lock.releaseLock();}}
function getHeats_(){const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.HEATS);if(!sheet||sheet.getLastRow()<2)return[];let width=Math.min(Math.max(sheet.getLastColumn(),10),16);return sheet.getRange(2,1,sheet.getLastRow()-1,width).getValues().reverse().slice(0,500).map(r=>({id:String(r[0]),heatNo:String(r[1]),grade:String(r[2]),furnace:String(r[3]),weight:Number(r[4]),status:String(r[5]),createdAt:r[6]instanceof Date?Utilities.formatDate(r[6],Session.getScriptTimeZone(),'dd MMM • HH:mm'):String(r[6]),createdBy:String(r[7]),additions:String(r[8]),chemistry:safeJson_(r[9]),completedAt:r[10]instanceof Date?Utilities.formatDate(r[10],Session.getScriptTimeZone(),'dd MMM • HH:mm'):String(r[10]||''),completedBy:String(r[11]||''),predicted:safeJson_(r[12]),gradeRevision:String(r[13]||''),calculatorVersion:String(r[14]||'')}));}
function getGrades_(){const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.GRADES);if(!sheet||sheet.getLastRow()<2)return[];return sheet.getRange(2,1,sheet.getLastRow()-1,71).getValues().filter(r=>r[0]&&r[70]!==false).map(r=>{const limits={};ELEMENTS.forEach((el,i)=>{const j=4+i*4,a=Number(r[j])||0,b=Number(r[j+1])||0,c=Number(r[j+2])||0,d=Number(r[j+3])||0;if(a||b||c||d)limits[el]={standardMin:a,targetMin:b,targetMax:c,standardMax:d};});return{name:String(r[0]),mode:String(r[1]),balance:String(r[2]),correctionBase:String(r[3]),limits,warningCorrection:Number(r[64])||0,approvalCorrection:Number(r[65])||0,maximumCorrection:Number(r[66])||0,rounding:Number(r[67])||.1,instructions:String(r[68]||''),revision:String(r[69]||'')};});}
function getMaterials_(){const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.MATERIALS);if(!sheet||sheet.getLastRow()<2)return[];return sheet.getRange(2,1,sheet.getLastRow()-1,43).getValues().filter(r=>r[0]&&r[1]!==false).map(r=>{const composition={},elementRecovery={};ELEMENTS.forEach((el,i)=>{const value=Number(r[5+i])||0,rec=Number(r[28+i])||0;if(value)composition[el]=value;if(rec)elementRecovery[el]=rec;});return{name:String(r[0]),active:r[1]!==false,primaryElement:String(r[2]),isDefault:r[3]===true,recovery:Number(r[4])||0,composition,notes:String(r[20]||''),rounding:Number(r[21])||0,maxStage:Number(r[22])||0,approvalAbove:Number(r[23])||0,sequence:Number(r[24])||99,minTemp:Number(r[25])||0,maxTemp:Number(r[26])||0,revision:String(r[27]||''),elementRecovery};});}
function getMaterialMaps_(){const sheet=SpreadsheetApp.getActive().getSheetByName(SHEETS.MAP);if(!sheet||sheet.getLastRow()<2)return[];return sheet.getRange(2,1,sheet.getLastRow()-1,6).getValues().filter(r=>r[0]&&r[1]&&r[5]!==false).map(r=>({grade:String(r[0]),element:String(r[1]),preferred:String(r[2]||''),alternative:String(r[3]||''),selectable:r[4]===true,active:r[5]!==false}));}
function ensureHeaders_(sheet,headers){if(!sheet)throw new Error('Required sheet is missing.');let current=sheet.getLastColumn();if(current<headers.length)sheet.insertColumnsAfter(current,headers.length-current);sheet.getRange(1,1,1,headers.length).setValues([headers]);}
function getOrCreate_(ss,name,headers){let sheet=ss.getSheetByName(name);if(!sheet)sheet=ss.insertSheet(name);if(sheet.getLastRow()===0)sheet.getRange(1,1,1,headers.length).setValues([headers]);return sheet;}
function formatSheet_(sheet){sheet.setFrozenRows(1);sheet.getRange(1,1,1,sheet.getLastColumn()).setBackground('#17365d').setFontColor('#ffffff').setFontWeight('bold');sheet.autoResizeColumns(1,Math.min(sheet.getLastColumn(),12));}
function safeJson_(value){try{return typeof value==='object'&&value!==null?value:JSON.parse(value||'{}');}catch(_){return{};}}
function json_(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
